# Generated by Django 3.2.7 on 2021-11-16 08:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='taskEnd',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 8, 57, 57, 982843)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='taskStart',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
